// <auto-generated/>

using Microsoft.VisualBasic.PowerPacks;

namespace PremiumQuoteGenerator
{
    partial class Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Main));
            this.bindingSource1 = new System.Windows.Forms.BindingSource(this.components);
            this.premiumLabel = new System.Windows.Forms.Label();
            this.premiumValueLabel = new System.Windows.Forms.Label();
            this.startDateLabel = new System.Windows.Forms.Label();
            this.startDatePicker = new System.Windows.Forms.DateTimePicker();
            this.clearButton = new System.Windows.Forms.Button();
            this.claimsListBox = new System.Windows.Forms.ListBox();
            this.driversListBox = new System.Windows.Forms.ListBox();
            this.getQuoteButton = new System.Windows.Forms.Button();
            this.driverDetailsGroupBox = new System.Windows.Forms.GroupBox();
            this.button1 = new System.Windows.Forms.Button();
            this.dateOfBirthPicker = new System.Windows.Forms.DateTimePicker();
            this.removeDriverButton = new System.Windows.Forms.Button();
            this.newClaimDatePicker = new System.Windows.Forms.DateTimePicker();
            this.dateOfBirthLabel = new System.Windows.Forms.Label();
            this.addClaimButton = new System.Windows.Forms.Button();
            this.occupationComboBox = new System.Windows.Forms.ComboBox();
            this.driverNameField = new System.Windows.Forms.TextBox();
            this.newDriverOccupationLabel = new System.Windows.Forms.Label();
            this.newDriverNameLabel = new System.Windows.Forms.Label();
            this.addDriverButton = new System.Windows.Forms.Button();
            this.driverListBoxLabel = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).BeginInit();
            this.driverDetailsGroupBox.SuspendLayout();
            this.SuspendLayout();
            // 
            // premiumLabel
            // 
            this.premiumLabel.AutoSize = true;
            this.premiumLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.premiumLabel.Location = new System.Drawing.Point(47, 275);
            this.premiumLabel.Name = "premiumLabel";
            this.premiumLabel.Size = new System.Drawing.Size(139, 25);
            this.premiumLabel.TabIndex = 25;
            this.premiumLabel.Text = "Their Premium";
            // 
            // premiumValueLabel
            // 
            this.premiumValueLabel.AutoSize = true;
            this.premiumValueLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F);
            this.premiumValueLabel.Location = new System.Drawing.Point(46, 305);
            this.premiumValueLabel.Name = "premiumValueLabel";
            this.premiumValueLabel.Size = new System.Drawing.Size(73, 31);
            this.premiumValueLabel.TabIndex = 24;
            this.premiumValueLabel.Text = "£--.--";
            // 
            // startDateLabel
            // 
            this.startDateLabel.AutoSize = true;
            this.startDateLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.startDateLabel.Location = new System.Drawing.Point(30, 22);
            this.startDateLabel.Name = "startDateLabel";
            this.startDateLabel.Size = new System.Drawing.Size(156, 25);
            this.startDateLabel.TabIndex = 23;
            this.startDateLabel.Text = "Policy Start Date";
            // 
            // startDatePicker
            // 
            this.startDatePicker.CustomFormat = "dd/mm/yyyy";
            this.startDatePicker.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.startDatePicker.Location = new System.Drawing.Point(257, 22);
            this.startDatePicker.Name = "startDatePicker";
            this.startDatePicker.Size = new System.Drawing.Size(258, 30);
            this.startDatePicker.TabIndex = 22;
            this.startDatePicker.Value = new System.DateTime(2016, 8, 2, 0, 0, 0, 0);
            this.startDatePicker.ValueChanged += new System.EventHandler(this.StartDate_Updated);
            // 
            // clearButton
            // 
            this.clearButton.BackColor = System.Drawing.Color.PaleGoldenrod;
            this.clearButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.clearButton.Location = new System.Drawing.Point(209, 387);
            this.clearButton.Name = "clearButton";
            this.clearButton.Size = new System.Drawing.Size(106, 42);
            this.clearButton.TabIndex = 21;
            this.clearButton.Text = "Clear";
            this.clearButton.UseVisualStyleBackColor = false;
            this.clearButton.Click += new System.EventHandler(this.ClearButton_Click);
            // 
            // claimsListBox
            // 
            this.claimsListBox.FormattingEnabled = true;
            this.claimsListBox.ItemHeight = 16;
            this.claimsListBox.Location = new System.Drawing.Point(442, 89);
            this.claimsListBox.Name = "claimsListBox";
            this.claimsListBox.Size = new System.Drawing.Size(306, 116);
            this.claimsListBox.TabIndex = 20;
            // 
            // driversListBox
            // 
            this.driversListBox.FormattingEnabled = true;
            this.driversListBox.ItemHeight = 16;
            this.driversListBox.Location = new System.Drawing.Point(52, 89);
            this.driversListBox.Name = "driversListBox";
            this.driversListBox.Size = new System.Drawing.Size(390, 116);
            this.driversListBox.TabIndex = 19;
            this.driversListBox.SelectedIndexChanged += new System.EventHandler(this.DriversList_Selected_Index_Changed);
            // 
            // getQuoteButton
            // 
            this.getQuoteButton.BackColor = System.Drawing.Color.LightGreen;
            this.getQuoteButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.getQuoteButton.Location = new System.Drawing.Point(52, 387);
            this.getQuoteButton.Name = "getQuoteButton";
            this.getQuoteButton.Size = new System.Drawing.Size(143, 42);
            this.getQuoteButton.TabIndex = 17;
            this.getQuoteButton.Text = "Get Quote";
            this.getQuoteButton.UseVisualStyleBackColor = false;
            this.getQuoteButton.Click += new System.EventHandler(this.GetQuoteButton_Click);
            // 
            // driverDetailsGroupBox
            // 
            this.driverDetailsGroupBox.Controls.Add(this.button1);
            this.driverDetailsGroupBox.Controls.Add(this.dateOfBirthPicker);
            this.driverDetailsGroupBox.Controls.Add(this.removeDriverButton);
            this.driverDetailsGroupBox.Controls.Add(this.newClaimDatePicker);
            this.driverDetailsGroupBox.Controls.Add(this.dateOfBirthLabel);
            this.driverDetailsGroupBox.Controls.Add(this.addClaimButton);
            this.driverDetailsGroupBox.Controls.Add(this.occupationComboBox);
            this.driverDetailsGroupBox.Controls.Add(this.driverNameField);
            this.driverDetailsGroupBox.Controls.Add(this.newDriverOccupationLabel);
            this.driverDetailsGroupBox.Controls.Add(this.newDriverNameLabel);
            this.driverDetailsGroupBox.Enabled = false;
            this.driverDetailsGroupBox.Location = new System.Drawing.Point(372, 214);
            this.driverDetailsGroupBox.Name = "driverDetailsGroupBox";
            this.driverDetailsGroupBox.Size = new System.Drawing.Size(376, 218);
            this.driverDetailsGroupBox.TabIndex = 18;
            this.driverDetailsGroupBox.TabStop = false;
            this.driverDetailsGroupBox.Text = "Driver Details";
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.PaleGoldenrod;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.button1.Location = new System.Drawing.Point(22, 173);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(161, 34);
            this.button1.TabIndex = 13;
            this.button1.Text = "Delete Claim";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.DeleteClaimButton_Click);
            // 
            // dateOfBirthPicker
            // 
            this.dateOfBirthPicker.Location = new System.Drawing.Point(189, 91);
            this.dateOfBirthPicker.Name = "dateOfBirthPicker";
            this.dateOfBirthPicker.Size = new System.Drawing.Size(169, 22);
            this.dateOfBirthPicker.TabIndex = 12;
            this.dateOfBirthPicker.ValueChanged += new System.EventHandler(this.DriverDateOfBirth_Updated);
            // 
            // removeDriverButton
            // 
            this.removeDriverButton.BackColor = System.Drawing.Color.PaleGoldenrod;
            this.removeDriverButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.removeDriverButton.Location = new System.Drawing.Point(189, 173);
            this.removeDriverButton.Name = "removeDriverButton";
            this.removeDriverButton.Size = new System.Drawing.Size(169, 34);
            this.removeDriverButton.TabIndex = 11;
            this.removeDriverButton.Text = "Delete Driver";
            this.removeDriverButton.UseVisualStyleBackColor = false;
            this.removeDriverButton.Click += new System.EventHandler(this.DeleteDriverButton_Click);
            // 
            // newClaimDatePicker
            // 
            this.newClaimDatePicker.Location = new System.Drawing.Point(22, 137);
            this.newClaimDatePicker.Name = "newClaimDatePicker";
            this.newClaimDatePicker.Size = new System.Drawing.Size(164, 22);
            this.newClaimDatePicker.TabIndex = 7;
            // 
            // dateOfBirthLabel
            // 
            this.dateOfBirthLabel.AutoSize = true;
            this.dateOfBirthLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.dateOfBirthLabel.Location = new System.Drawing.Point(18, 90);
            this.dateOfBirthLabel.Name = "dateOfBirthLabel";
            this.dateOfBirthLabel.Size = new System.Drawing.Size(105, 20);
            this.dateOfBirthLabel.TabIndex = 9;
            this.dateOfBirthLabel.Text = "Date of Birth";
            // 
            // addClaimButton
            // 
            this.addClaimButton.BackColor = System.Drawing.Color.PaleGreen;
            this.addClaimButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.addClaimButton.Location = new System.Drawing.Point(202, 130);
            this.addClaimButton.Name = "addClaimButton";
            this.addClaimButton.Size = new System.Drawing.Size(156, 34);
            this.addClaimButton.TabIndex = 6;
            this.addClaimButton.Text = "+ Add Claim";
            this.addClaimButton.UseVisualStyleBackColor = false;
            this.addClaimButton.Click += new System.EventHandler(this.AddClaimButton_Click);
            // 
            // occupationComboBox
            // 
            this.occupationComboBox.FormattingEnabled = true;
            this.occupationComboBox.Location = new System.Drawing.Point(189, 61);
            this.occupationComboBox.Name = "occupationComboBox";
            this.occupationComboBox.Size = new System.Drawing.Size(169, 24);
            this.occupationComboBox.TabIndex = 7;
            this.occupationComboBox.SelectedIndexChanged += new System.EventHandler(this.DriverOccupation_Updated);
            this.occupationComboBox.TextUpdate += new System.EventHandler(this.DriverOccupation_Updated);
            // 
            // driverNameField
            // 
            this.driverNameField.Location = new System.Drawing.Point(189, 33);
            this.driverNameField.Name = "driverNameField";
            this.driverNameField.Size = new System.Drawing.Size(169, 22);
            this.driverNameField.TabIndex = 8;
            this.driverNameField.TextChanged += new System.EventHandler(this.DriverName_Updated);
            // 
            // newDriverOccupationLabel
            // 
            this.newDriverOccupationLabel.AutoSize = true;
            this.newDriverOccupationLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.newDriverOccupationLabel.Location = new System.Drawing.Point(18, 61);
            this.newDriverOccupationLabel.Name = "newDriverOccupationLabel";
            this.newDriverOccupationLabel.Size = new System.Drawing.Size(94, 20);
            this.newDriverOccupationLabel.TabIndex = 6;
            this.newDriverOccupationLabel.Text = "Occupation";
            // 
            // newDriverNameLabel
            // 
            this.newDriverNameLabel.AutoSize = true;
            this.newDriverNameLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F);
            this.newDriverNameLabel.Location = new System.Drawing.Point(18, 36);
            this.newDriverNameLabel.Name = "newDriverNameLabel";
            this.newDriverNameLabel.Size = new System.Drawing.Size(53, 20);
            this.newDriverNameLabel.TabIndex = 5;
            this.newDriverNameLabel.Text = "Name";
            // 
            // addDriverButton
            // 
            this.addDriverButton.BackColor = System.Drawing.Color.PaleGreen;
            this.addDriverButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.addDriverButton.Location = new System.Drawing.Point(52, 211);
            this.addDriverButton.Name = "addDriverButton";
            this.addDriverButton.Size = new System.Drawing.Size(143, 36);
            this.addDriverButton.TabIndex = 5;
            this.addDriverButton.Text = "+ Add Driver";
            this.addDriverButton.UseVisualStyleBackColor = false;
            this.addDriverButton.Click += new System.EventHandler(this.AddDriverButton_Click);
            // 
            // driverListBoxLabel
            // 
            this.driverListBoxLabel.AutoSize = true;
            this.driverListBoxLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.driverListBoxLabel.Location = new System.Drawing.Point(30, 61);
            this.driverListBoxLabel.Name = "driverListBoxLabel";
            this.driverListBoxLabel.Size = new System.Drawing.Size(73, 25);
            this.driverListBoxLabel.TabIndex = 15;
            this.driverListBoxLabel.Text = "Drivers";
            // 
            // Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.SystemColors.Window;
            this.ClientSize = new System.Drawing.Size(781, 444);
            this.Controls.Add(this.addDriverButton);
            this.Controls.Add(this.premiumLabel);
            this.Controls.Add(this.premiumValueLabel);
            this.Controls.Add(this.startDateLabel);
            this.Controls.Add(this.startDatePicker);
            this.Controls.Add(this.clearButton);
            this.Controls.Add(this.claimsListBox);
            this.Controls.Add(this.driversListBox);
            this.Controls.Add(this.getQuoteButton);
            this.Controls.Add(this.driverDetailsGroupBox);
            this.Controls.Add(this.driverListBoxLabel);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Main";
            this.Text = "Premium Quote Generator";
            this.Load += new System.EventHandler(this.Main_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bindingSource1)).EndInit();
            this.driverDetailsGroupBox.ResumeLayout(false);
            this.driverDetailsGroupBox.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.BindingSource bindingSource1;
        private System.Windows.Forms.Label premiumLabel;
        private System.Windows.Forms.Label premiumValueLabel;
        private System.Windows.Forms.Label startDateLabel;
        private System.Windows.Forms.DateTimePicker startDatePicker;
        private System.Windows.Forms.Button clearButton;
        private System.Windows.Forms.ListBox claimsListBox;
        private System.Windows.Forms.ListBox driversListBox;
        private System.Windows.Forms.Button getQuoteButton;
        private System.Windows.Forms.GroupBox driverDetailsGroupBox;
        private System.Windows.Forms.DateTimePicker newClaimDatePicker;
        private System.Windows.Forms.Button addClaimButton;
        private System.Windows.Forms.TextBox driverNameField;
        private System.Windows.Forms.ComboBox occupationComboBox;
        private System.Windows.Forms.Label newDriverOccupationLabel;
        private System.Windows.Forms.Label newDriverNameLabel;
        private System.Windows.Forms.Button addDriverButton;
        private System.Windows.Forms.Label driverListBoxLabel;
        private System.Windows.Forms.Button removeDriverButton;
        private System.Windows.Forms.Label dateOfBirthLabel;
        private System.Windows.Forms.DateTimePicker dateOfBirthPicker;
        private System.Windows.Forms.Button button1;
    }
}

